# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# pttoraster.py
# Created on: 2016-08-22 18:39:31.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import sys
import arcpy
from arcpy import env

def pointtoraster(datadir,pointfile,refraster,outfile):
    # Set environment settings
    env.workspace = datadir

    # Local variables:
    testdp2 =  env.workspace+"/"+pointfile
    testwt_tif = env.workspace+"/"+outfile
    arcpy.env.extent = env.workspace+"/"+refraster
    arcpy.env.outputCoordinateSystem =  env.workspace+"/"+refraster
    cellsize=30
    # Process: Feature to Raster
    arcpy.FeatureToRaster_conversion(testdp2, "Gval", testwt_tif,cellsize)
if __name__ == '__main__':
    datadir = sys.argv[1]
    pointfile = sys.argv[2]
    refraster=sys.argv[3]
    outfile=sys.argv[4]
    pointtoraster(datadir,pointfile,refraster,outfile)


